DROP DATABASE IF EXISTS freddysFiles;
create database freddysFiles;
use freddysFiles;

DROP TABLE IF EXISTS Products;
CREATE TABLE Products (
	ProductName varchar(255),
    ProductImageUrl varchar(255),
    ProductDescription text(255),
    Price decimal(10, 2),
    SystemRequirements varchar(1000));
    
INSERT INTO Products 
(ProductName, ProductImageURL, ProductDescription, Price, SystemRequirements) VALUES 
('Dragon Ball Z: Kakarot', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\dbzKakarot.jpg', 'Relive the story of Goku and other Z Fighters in DRAGON BALL Z: KAKAROT! Beyond the epic battles, experience life in the DRAGON BALL Z world as you fight, fish, eat, and train with Goku, Gohan, Vegeta and others', 59.99, 'OS: Windows 7 SP1 64-bit, Processor: Intel Core i5-2400 or AMD Phenom II X6 1100T, Graphics: GeForce GTX 750 Ti or Radeon HD 7950, Memory: 4 GB RAM, DirectX: 11 Compatible video card or equivalent, Hard-drive space: 36 GB'),
('Forza Horizon 4', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\forzahorizon4.jpg', 'Forza Horizon is an action racing game set on the epic open roads of Colorado with a thrilling music festival backdrop. Combining stunning graphics and cutting-edge music with legendary Forza authenticity and a superb collection of cars to drive, Forza Horizon is an open-world automotive playground that puts a spotlight on speed, style, and the freedom of the open road. Check out the trailer for Forza Horizon. This is where cars belong', 39.99, 'OS: Windows 10 version 15063.0 or higher, Processor: Intel i3-4170 @ 3.7Ghz or Intel i5 750 @ 2.67Ghz, Graphics card: Nvidia GTX 650 Ti or Nvidia GT 740 or AMD R7 250x, Memory: 8 GB, DirectX: 12 Compatible video card or equivalent, Hard-drive space: 76 GB'),
('Star Wars Jedi: Fallen Order', '\\SprintProject3_Freddys-Files_eCommerce\\src\main\\webapp\\images\\star-wars-jedi-wallpaper.jpg', 'Empire seeks to eradicate all Jedi after the execution of Order 66. You, a Jedi Padawan-turned-fugitive, must fight for your survival as you explore the mysteries of a long-extinct civilization in hopes of rebuilding the Jedi Order', 45.99, 'OS: 64-bit Windows 7/8.1/10, Processor (AMD): FX-6100 or Equivalent / (Intel): i3-3220 or Equivalent, Memory: 8 GB, Graphics card (AMD): Radeon HD 7750 or Equivalent / (NVIDIA): GeForce GTX 650 or Equivalent, DirectX: 11 Compatible video card or equivalent, Hard-drive space: 55 GB'),
('Mordhau', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\mordhau.jpg', 'MORDHAU is a multiplayer medieval slasher. Create your mercenary and fight in brutal battles where you will experience fast paced combat, castle sieges, cavalry charges, and more.', 30.00, 'OS: Windows 7 64 Bit, Windows 8 64 Bit, Windows 10 64 Bit, Processor: Intel Core i5 - 4670 or AMD equivalent, Memory: 8 GB RAM, Graphics: NVIDIA GTX 680 or AMD equivalent, DirectX: Version 11, Storage: 20 GB available space'),
('Mount & Blade 2: Banner Lord', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\bannerlord-header.jpg', 'The horns sound, the ravens gather. An empire is torn by civil war. Beyond its borders, new kingdoms rise. Gird on your sword, don your armour, summon your followers and ride forth to win glory on the battlefields of Calradia. Establish your hegemony and create a new world out of the ashes of the old.', 45.99, 'Windows 7 (64-bit only), Processor: Intel® Core™ i3-8100 / AMD Ryzen™ 3 1200, Memory: 6 GB RAM, Graphics: Intel® UHD Graphics 630 / NVIDIA® GeForce® GTX 660 2GB / AMD Radeon™ HD 7850 2GB, 60 GB available space'),
('Need For Speed Heat', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\nfsHeat.jpg', 'In Need for Speed Heat, the lines of the law fade when the sun starts to set. By daylight, compete in the Speedhunter Showdown, a series of sanctioned events where you can earn Bank to customize your personal fleet of cars. When your ride’s styled just right, ramp up the intensity at night. Enter illicit street races with your die-hard crew but stay ready – rogue cops are waiting. Take chances, burn competitors to increase your Rep, and risk it all for underground glory', 29.99, 'OS: Windows 10, Processor: FX-6350 or equivalent / Core i5-3570 or equivalent, Memory: 8 GB, Graphics card (AMD): Radeon 7970/Radeon R9 280x or equivalent, (NVIDIA): GeForce GTX 760 or equivalent, Hard-drive space: 50 GB'),
('One Piece: Pirate Warriors 4', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\opWarriors4.jpg', 'ONE PIECE: PIRATE WARRIORS 4 is the latest evolution of PIRATE WARRIORS action! Based on the concept of "experiencing a real ONE PIECE battlefield," buildings will come crashing down during the action and attacks will throw up smoke and dust, placing you in the thick of the ONE PIECE world!', 45.99, 'OS: Windows 10, 64bits, Processor: Intel Core i5 3450 / AMD Ryzen 3 1300X, Graphics: NVIDIA GeForce GTX 660 (2GB) / AMD Radeon HD 7870 (2GB), Memory: 8 GB RAM, Hard-drive space: 25 GB'),
('Battlefield 5', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\bf5.jpg', 'Enter mankind’s greatest conflict with Battlefield™ V. The Battlefield series goes back to its roots in a never-before-seen portrayal of World War 2', 28.99, 'OS: 64-bit Windows 7, Windows 8.1 and Windows 10, Graphics card (NVIDIA): NVIDIA GeForce® GTX 1050 / NVIDIA GeForce® GTX 660 2GB / Graphics card (AMD): AMD Radeon™ RX 560 / HD 7850 2GB, Memory: 8GB RAM, Hard-drive space: 50GB'),
('Call Of Duty: Modern Warfare (2019)', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\CodMW.jpg', 'The stakes have never been higher as players take on the role of lethal Tier One operators in a heart-racing saga that will affect the global balance of power. Developed by the studio that started it all, Infinity Ward delivers an epic reimagining of the iconic Modern Warfare® series from the ground up.', 45.00, 'OS: Windows 7 64-Bit (SP1) or Windows 10 64-Bit, Processor: Intel Core i3-4340 or AMD FX-6300, Graphics: NVIDIA GeForce GTX 670 / GeForce GTX 1650 or Radeon HD 7950,Hard-drive space: 175GB'),
('Cyberpunk 2077', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\Cyberpunk_2077.jpg', 'Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.', 59.99, 'OS: Windows 7 64-Bit (SP1) or Windows 10 64-Bit, Processor: Intel Core i3-4340 or AMD FX-6300, Graphics: NVIDIA GeForce GTX 670 / GeForce GTX 1650 or Radeon HD 7950, Hard-drive space: 175GB'),
('Doom Eternal', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\doometernal2.png', 'Hell’s armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.', 50.00, 'OS: 64-bit Windows 7 / 64-Bit Windows 10, Processor: Intel Core i5 @ 3.3 GHz or better, or AMD Ryzen 3 @ 3.1 GHz or better, Graphics: NVIDIA GeForce GTX 1050Ti (4GB), GTX 1060 (3GB), GTX 1650 (4GB) or AMD Radeon R9 280(3GB), AMD Radeon R9 290 (4GB), RX 470 (4GB),Memory: 8 GB RAM, Storage: 50 GB available space'),
('Legend of Zelda: Breath of he Wild', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\zeldaBreathOfTheWild.jpg', 'No kingdom. No memories. After a 100-year slumber, Link wakes up alone in a world he no longer remembers. Now the legendary hero must explore a vast and dangerous land and regain his memories before Hyrule is lost forever. Armed only with what he can scavenge, Link sets out to find answers and the resources needed to survive.', 45.99, 'Get a Nintendo Switch scrub'),
('Red Dead Redemption 2', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\reddead2.jpg', 'Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Also includes access to the shared living world of Red Dead Online.', 50.00, 'OS: Windows 7 - Service Pack 1 (6.1.7601), Processor: Intel® Core™ i5-2500K / AMD FX-6300, Graphics Card: Nvidia GeForce GTX 770 2GB / AMD Radeon R9 280 3GB, Memory: 8 GB RAM, Storage: HDD Space: 150GB'),
('Rocket League', '\\SprintProject3_Freddys-Files_eCommerce\\src\\main\\webapp\\images\\rocketLeague.jpg', 'Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition. Rocket League includes casual and competitive Online Matches, a fully-featured offline Season Mode, special “Mutators” that let you change the rules entirely, hockey and basketball-inspired Extra Modes, and more than 500 trillion possible cosmetic customization combinations.', 19.99, 'OS: Windows 7 (64 bit) or Newer (64 bit) Windows OS, Processor: 2.5 GHz Dual core, Graphics: NVIDIA GeForce 760, AMD Radeon R7 270X, or better, Memory: 4 GB RAM, DirectX: 12 Compatible video card or equivalent, Hard-drive space: 20 GB');

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	UserName varchar(255),
    UserPassword varchar(255));
    
INSERT INTO Users
(UserName, UserPassword) VALUES
('freddy', 'password'),
('steven', 'password'),
('calvin', 'password'),
('cole', 'password');

select * from Users;
select * from Products;